//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPractice1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmenTable
    {
        public DepartmenTable()
        {
            this.EmployeeTables = new HashSet<EmployeeTable>();
        }
    
        public int Id { get; set; }
        public string Name1 { get; set; }
        public string Location1 { get; set; }
    
        public virtual ICollection<EmployeeTable> EmployeeTables { get; set; }
    }
}
